In [1]:
import pandas as pd

In [2]:
titanic_train = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv")
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
dy = titanic_train.dtypes
dy

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
dy['PassengerId']

dtype('int64')

In [7]:
dy[0]

C:\Users\Satynarayan Maurya\AppData\Local\Temp\ipykernel_14920\1032043665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dy[0]


dtype('int64')

In [8]:
dy[0:4]

PassengerId     int64
Survived        int64
Pclass          int64
Name           object
dtype: object

In [9]:
titanic_train['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [11]:
titanic_train['Age'][0:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [12]:
titanic_train['Age'][::-1]

890    32.0
889    26.0
888     NaN
887    19.0
886    27.0
       ... 
4      35.0
3      35.0
2      26.0
1      38.0
0      22.0
Name: Age, Length: 891, dtype: float64

In [18]:
titanic_train['Age'][::2]

0      22.0
2      26.0
4      35.0
6      54.0
8      27.0
       ... 
882    22.0
884    25.0
886    27.0
888     NaN
890    32.0
Name: Age, Length: 446, dtype: float64

In [20]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [23]:
# Find the name of the passenger which paid maximum fare
import numpy as np 
max_fare = np.where(titanic_train["Fare"] == max(titanic_train['Fare']))
max_fare

(array([258, 679, 737]),)

In [27]:
titanic_train.iloc[max_fare]

PassengerId  Survived  Pclass                                Name  \
258          259         1       1                    Ward, Miss. Anna   
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez   
737          738         1       1              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292          NaN        C  
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C  
737    male  35.0      0      0  PC 17755  512.3292         B101        C

In [28]:
titanic_train.iloc[max_fare].Name

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [38]:
titanic_train['Cabin'].isnull()

0       True
1      False
2       True
3      False
4       True
       ...  
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [42]:
# Find the age whose cabin is NaN
titanic_train[titanic_train['Cabin'].isnull()].Age.index

Index([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,
       ...
       878, 880, 881, 882, 883, 884, 885, 886, 888, 890],
      dtype='int64', length=687)

In [43]:
# Find that Passenger Name which survived and they are male
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [57]:
np.where((titanic_train['Survived'] == 1) & (titanic_train['Sex'] == 'male'))

(array([ 17,  21,  23,  36,  55,  65,  74,  78,  81,  97, 107, 125, 127,
        146, 165, 183, 187, 193, 204, 207, 209, 220, 224, 226, 248, 261,
        267, 271, 283, 286, 288, 298, 301, 305, 338, 340, 348, 370, 390,
        391, 400, 407, 414, 429, 430, 444, 445, 447, 449, 453, 455, 460,
        484, 489, 507, 509, 510, 512, 543, 547, 549, 550, 553, 569, 570,
        572, 579, 587, 599, 604, 607, 621, 622, 630, 632, 643, 645, 647,
        660, 664, 673, 679, 681, 690, 692, 701, 707, 709, 712, 724, 737,
        740, 744, 751, 755, 762, 788, 802, 803, 804, 821, 827, 828, 831,
        838, 839, 857, 869, 889]),)

In [63]:
titanic_train.iloc[np.where((titanic_train['Survived'] == 1) & (titanic_train['Sex'] == 'male'))][['Name','Sex','Survived']] # These people are survived 

Name   Sex  Survived
17      Williams, Mr. Charles Eugene  male         1
21             Beesley, Mr. Lawrence  male         1
23      Sloper, Mr. William Thompson  male         1
36                  Mamee, Mr. Hanna  male         1
55                 Woolner, Mr. Hugh  male         1
..                               ...   ...       ...
838                  Chip, Mr. Chang  male         1
839             Marechal, Mr. Pierre  male         1
857           Daly, Mr. Peter Denis   male         1
869  Johnson, Master. Harold Theodor  male         1
889            Behr, Mr. Karl Howell  male         1

[109 rows x 3 columns]

In [64]:
# Some more concept about Series and Data Frames

In [65]:
l = [1,2,3,4,5]

In [66]:
pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [67]:
d = {"name":"Satya","title":"Maurya","email_id":"abcd@gmail.com"}

In [71]:
pd.DataFrame(d,index=[0,1,2])

name   title        email_id
0  Satya  Maurya  abcd@gmail.com
1  Satya  Maurya  abcd@gmail.com
2  Satya  Maurya  abcd@gmail.com

In [72]:
pd.Series(d)

name                 Satya
title               Maurya
email_id    abcd@gmail.com
dtype: object

In [73]:
import numpy as np 
arr = np.random.randn(3,4)
arr

array([[ 0.70703172,  0.53970903,  0.43842736,  0.47009746],
       [ 0.8563298 ,  0.48671355, -0.36309295, -0.63472304],
       [-0.12121537,  1.02701924,  0.32717525,  1.23643196]])

In [74]:
pd.DataFrame(arr)

0         1         2         3
0  0.707032  0.539709  0.438427  0.470097
1  0.856330  0.486714 -0.363093 -0.634723
2 -0.121215  1.027019  0.327175  1.236432

In [75]:
pd.Series(np.array([1,2,3,4,5]))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [76]:
# We can give our own indexes like
pd.Series(np.array([1,2,3,4,5],),index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [82]:
df = pd.DataFrame(np.random.randint(3,6,(4,5)))
df

0  1  2  3  4
0  4  4  5  4  5
1  4  5  4  5  4
2  4  3  4  4  5
3  3  4  4  5  5

In [83]:
df.iloc[[2,3],[3,4]]

3  4
2  4  5
3  5  5

In [84]:
df

0  1  2  3  4
0  4  4  5  4  5
1  4  5  4  5  4
2  4  3  4  4  5
3  3  4  4  5  5

In [85]:
df['new'] = df[0] + df[1]

In [86]:
df

0  1  2  3  4  new
0  4  4  5  4  5    8
1  4  5  4  5  4    9
2  4  3  4  4  5    7
3  3  4  4  5  5    7

In [87]:
df.drop(0)

0  1  2  3  4  new
1  4  5  4  5  4    9
2  4  3  4  4  5    7
3  3  4  4  5  5    7

In [90]:
df.drop(1,axis=1,inplace=True)

In [92]:
df

0  2  3  4  new
0  4  5  4  5    8
1  4  4  5  4    9
2  4  4  4  5    7
3  3  4  5  5    7

In [96]:
df = pd.DataFrame(np.random.randn(4,5),index=['a','b','c','d'], columns=['p','q','r','s','t'])
df

p         q         r         s         t
a  1.085821 -0.494517 -1.944153  0.214876  0.692459
b -0.714740  0.790952 -0.068197 -0.264658 -0.565078
c -0.598275  1.329250  1.481541 -0.891615 -1.491930
d -0.439288 -1.780681 -1.170182  1.542106 -1.627461

In [99]:
# Lets we have to find all the negative value from this data frame
neg_values = df.values[df.values<0]
neg_values

array([-0.49451733, -1.94415331, -0.71474024, -0.06819732, -0.26465773,
       -0.56507842, -0.59827534, -0.89161502, -1.49192998, -0.439288  ,
       -1.78068117, -1.17018248, -1.62746077])

In [103]:
df.values[df.iloc[0:5]<0]  # This is also one more way of finding negative value from that column

array([-0.49451733, -1.94415331, -0.71474024, -0.06819732, -0.26465773,
       -0.56507842, -0.59827534, -0.89161502, -1.49192998, -0.439288  ,
       -1.78068117, -1.17018248, -1.62746077])

In [105]:
# The requirement is print the row as well as column of this corresponding negative values
for i in df.columns:
    for j in df.index:
        if(df.loc[j,i]<0):
            print(j,i,df.loc[j,i])

b p -0.7147402398545136
c p -0.5982753413273435
d p -0.43928800296515735
a q -0.4945173325239881
d q -1.7806811727744563
a r -1.9441533140970302
b r -0.06819731801956028
d r -1.1701824824894163
b s -0.2646577323161448
c s -0.8916150244280623
b t -0.5650784227108651
c t -1.4919299795043053
d t -1.6274607699368833


In [108]:
d = {'key1':[1,2,3,4,np.nan],'key2':['Satya','maurya',np.nan,np.nan,2],'key3':[4,5,6,np.nan,9]}
df = pd.DataFrame(d)
df

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     NaN   6.0
3   4.0     NaN   NaN
4   NaN       2   9.0

In [109]:
df.dropna()  # It will remove all the row which contain any NaN value

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0

In [110]:
df

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     NaN   6.0
3   4.0     NaN   NaN
4   NaN       2   9.0

In [112]:
df.dropna(axis=1)   # This will remove the column which contain any NaN value

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [113]:
df

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     NaN   6.0
3   4.0     NaN   NaN
4   NaN       2   9.0

In [115]:
df.dropna(thresh=0)   # This will remove that row which does not have atleast 0 NaN value

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     NaN   6.0
3   4.0     NaN   NaN
4   NaN       2   9.0

In [116]:
df.dropna(thresh=1)   # This will remove that row which does not have atleast 1 NaN value

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     NaN   6.0
3   4.0     NaN   NaN
4   NaN       2   9.0

In [117]:
df.dropna(thresh=2)   # This will remove that row which does not have atleast 2 NaN value

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     NaN   6.0
4   NaN       2   9.0

In [118]:
df.dropna(thresh=3)   # This will remove that row which does not have atleast 3 NaN value

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0

In [119]:
df

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     NaN   6.0
3   4.0     NaN   NaN
4   NaN       2   9.0

In [121]:
df.fillna(value=df['key1'].mean())       # This will fill all the NaN value to the mean of the column key1

key1    key2  key3
0   1.0   Satya   4.0
1   2.0  maurya   5.0
2   3.0     2.5   6.0
3   4.0     2.5   2.5
4   2.5       2   9.0

In [123]:
d1 = {
    'name':['satya','abhi','harsh','abhi','harsh'],
    'email':['saty@gmail.com','abhi@gmail.com','harsh@gmail.com','abhi@gmail.com','harsh@gmail.com'],
    'salary':[100,200,500,200,500]
}

df2 = pd.DataFrame(d1)
df2

name            email  salary
0  satya   saty@gmail.com     100
1   abhi   abhi@gmail.com     200
2  harsh  harsh@gmail.com     500
3   abhi   abhi@gmail.com     200
4  harsh  harsh@gmail.com     500

In [126]:
# Now we are going to do some basic operation on this Data Frame
df2.groupby('name')['salary'].mean()

name
abhi     200.0
harsh    500.0
satya    100.0
Name: salary, dtype: float64

In [129]:
df2.groupby('email')['salary'].mean()

email
abhi@gmail.com     200.0
harsh@gmail.com    500.0
saty@gmail.com     100.0
Name: salary, dtype: float64

In [130]:
df2.groupby('name').describe()

salary                                               
       count   mean  std    min    25%    50%    75%    max
name                                                       
abhi     2.0  200.0  0.0  200.0  200.0  200.0  200.0  200.0
harsh    2.0  500.0  0.0  500.0  500.0  500.0  500.0  500.0
satya    1.0  100.0  NaN  100.0  100.0  100.0  100.0  100.0

In [131]:
df2.groupby('name').describe().loc['harsh']

salary  count      2.0
        mean     500.0
        std        0.0
        min      500.0
        25%      500.0
        50%      500.0
        75%      500.0
        max      500.0
Name: harsh, dtype: float64

In [134]:
df2.groupby('name').describe().loc['harsh']['salary'][1]

C:\Users\Satynarayan Maurya\AppData\Local\Temp\ipykernel_14920\745050814.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df2.groupby('name').describe().loc['harsh']['salary'][1]


np.float64(500.0)

In [136]:
df2.groupby('name').describe().loc['harsh']['salary'].loc['mean']

np.float64(500.0)

In [139]:
df2.groupby('name').describe()

salary                                               
       count   mean  std    min    25%    50%    75%    max
name                                                       
abhi     2.0  200.0  0.0  200.0  200.0  200.0  200.0  200.0
harsh    2.0  500.0  0.0  500.0  500.0  500.0  500.0  500.0
satya    1.0  100.0  NaN  100.0  100.0  100.0  100.0  100.0

In [140]:
df2.groupby('name').describe().T

name           abhi  harsh  satya
salary count    2.0    2.0    1.0
       mean   200.0  500.0  100.0
       std      0.0    0.0    NaN
       min    200.0  500.0  100.0
       25%    200.0  500.0  100.0
       50%    200.0  500.0  100.0
       75%    200.0  500.0  100.0
       max    200.0  500.0  100.0

In [141]:
# Move to the next operation concatination
arr1 = np.random.randn(3,4)
arr1

array([[ 1.48952573, -0.72536079,  0.03710573,  0.32497359],
       [ 1.83703703, -0.22095293, -0.35271438, -1.19460252],
       [-0.42958367,  0.49266573,  0.01671966, -1.81800277]])

In [142]:
arr2 = np.random.randn(3,4)
arr2

array([[-0.44086044, -0.72573036,  0.91397107, -1.34168206],
       [-0.12347241,  0.28605118,  0.75484478,  0.26264704],
       [-1.18107509,  0.96728277, -0.10745138, -0.37975236]])

In [143]:
arr3 = np.random.randn(3,4)
arr3

array([[ 0.023148  ,  0.19281883,  0.1412354 , -1.09672127],
       [ 0.23585559,  0.13733502,  1.23103493,  1.26464088],
       [-0.1362123 ,  0.9310761 , -0.11675872, -1.0130482 ]])

In [144]:
df1 = pd.DataFrame(arr1,columns=['A','B','C','D'], index=[0,1,2])
df1

A         B         C         D
0  1.489526 -0.725361  0.037106  0.324974
1  1.837037 -0.220953 -0.352714 -1.194603
2 -0.429584  0.492666  0.016720 -1.818003

In [145]:
df2 = pd.DataFrame(arr2,columns=['A','B','C','D'], index=[0,1,2])
df2

A         B         C         D
0 -0.440860 -0.725730  0.913971 -1.341682
1 -0.123472  0.286051  0.754845  0.262647
2 -1.181075  0.967283 -0.107451 -0.379752

In [146]:
df3 = pd.DataFrame(arr3,columns=['A','B','C','D'], index=[0,1,2])
df3

A         B         C         D
0  0.023148  0.192819  0.141235 -1.096721
1  0.235856  0.137335  1.231035  1.264641
2 -0.136212  0.931076 -0.116759 -1.013048

In [148]:
# Concatinate these data frames into one
pd.concat([df1,df2,df3])       # As the default axis is 0 so this will concatinate in row 

A         B         C         D
0  1.489526 -0.725361  0.037106  0.324974
1  1.837037 -0.220953 -0.352714 -1.194603
2 -0.429584  0.492666  0.016720 -1.818003
0 -0.440860 -0.725730  0.913971 -1.341682
1 -0.123472  0.286051  0.754845  0.262647
2 -1.181075  0.967283 -0.107451 -0.379752
0  0.023148  0.192819  0.141235 -1.096721
1  0.235856  0.137335  1.231035  1.264641
2 -0.136212  0.931076 -0.116759 -1.013048

In [150]:
pd.concat([df1,df2,df3],axis=1)       # As the default axis is 1 so this will concatinate in column 

A         B         C         D         A         B         C  \
0  1.489526 -0.725361  0.037106  0.324974 -0.440860 -0.725730  0.913971   
1  1.837037 -0.220953 -0.352714 -1.194603 -0.123472  0.286051  0.754845   
2 -0.429584  0.492666  0.016720 -1.818003 -1.181075  0.967283 -0.107451   

          D         A         B         C         D  
0 -1.341682  0.023148  0.192819  0.141235 -1.096721  
1  0.262647  0.235856  0.137335  1.231035  1.264641  
2 -0.379752 -0.136212  0.931076 -0.116759 -1.013048

In [151]:
df4 = pd.concat([df1,df2,df3])
df4

A         B         C         D
0  1.489526 -0.725361  0.037106  0.324974
1  1.837037 -0.220953 -0.352714 -1.194603
2 -0.429584  0.492666  0.016720 -1.818003
0 -0.440860 -0.725730  0.913971 -1.341682
1 -0.123472  0.286051  0.754845  0.262647
2 -1.181075  0.967283 -0.107451 -0.379752
0  0.023148  0.192819  0.141235 -1.096721
1  0.235856  0.137335  1.231035  1.264641
2 -0.136212  0.931076 -0.116759 -1.013048

In [155]:
df4.iloc[0]  # As there are named indexes that means we give these indexes but in backend pandas create their indexes because the indexes can not be same

A    1.489526
B   -0.725361
C    0.037106
D    0.324974
Name: 0, dtype: float64

In [156]:
df4.loc[0]

A         B         C         D
0  1.489526 -0.725361  0.037106  0.324974
0 -0.440860 -0.725730  0.913971 -1.341682
0  0.023148  0.192819  0.141235 -1.096721

In [157]:
df5 = pd.concat([df1,df2,df3],axis=1)
df5

A         B         C         D         A         B         C  \
0  1.489526 -0.725361  0.037106  0.324974 -0.440860 -0.725730  0.913971   
1  1.837037 -0.220953 -0.352714 -1.194603 -0.123472  0.286051  0.754845   
2 -0.429584  0.492666  0.016720 -1.818003 -1.181075  0.967283 -0.107451   

          D         A         B         C         D  
0 -1.341682  0.023148  0.192819  0.141235 -1.096721  
1  0.262647  0.235856  0.137335  1.231035  1.264641  
2 -0.379752 -0.136212  0.931076 -0.116759 -1.013048

In [158]:
df5['A']

A         A         A
0  1.489526 -0.440860  0.023148
1  1.837037 -0.123472  0.235856
2 -0.429584 -1.181075 -0.136212

In [160]:
# Lets we want that the second A column data we are required
df5.iloc[:,4]   # This will give only the second A Column data

0   -0.440860
1   -0.123472
2   -1.181075
Name: A, dtype: float64

In [162]:
df11 = pd.DataFrame(arr2,columns=['A','B','C','D'], index=[0,1,2])
df11

A         B         C         D
0 -0.440860 -0.725730  0.913971 -1.341682
1 -0.123472  0.286051  0.754845  0.262647
2 -1.181075  0.967283 -0.107451 -0.379752

In [163]:
df22 = pd.DataFrame(arr2,columns=['A','B','C','D'], index=[3,4,5])
df22

A         B         C         D
3 -0.440860 -0.725730  0.913971 -1.341682
4 -0.123472  0.286051  0.754845  0.262647
5 -1.181075  0.967283 -0.107451 -0.379752

In [165]:
df6 = pd.concat([df11,df22],axis=1)
df6

A         B         C         D         A         B         C  \
0 -0.440860 -0.725730  0.913971 -1.341682       NaN       NaN       NaN   
1 -0.123472  0.286051  0.754845  0.262647       NaN       NaN       NaN   
2 -1.181075  0.967283 -0.107451 -0.379752       NaN       NaN       NaN   
3       NaN       NaN       NaN       NaN -0.440860 -0.725730  0.913971   
4       NaN       NaN       NaN       NaN -0.123472  0.286051  0.754845   
5       NaN       NaN       NaN       NaN -1.181075  0.967283 -0.107451   

          D  
0       NaN  
1       NaN  
2       NaN  
3 -1.341682  
4  0.262647  
5 -0.379752

In [166]:
df7 = pd.concat([df11,df22],axis=1).fillna(0)
df7

A         B         C         D         A         B         C  \
0 -0.440860 -0.725730  0.913971 -1.341682  0.000000  0.000000  0.000000   
1 -0.123472  0.286051  0.754845  0.262647  0.000000  0.000000  0.000000   
2 -1.181075  0.967283 -0.107451 -0.379752  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000 -0.440860 -0.725730  0.913971   
4  0.000000  0.000000  0.000000  0.000000 -0.123472  0.286051  0.754845   
5  0.000000  0.000000  0.000000  0.000000 -1.181075  0.967283 -0.107451   

          D  
0  0.000000  
1  0.000000  
2  0.000000  
3 -1.341682  
4  0.262647  
5 -0.379752

In [173]:
np.random.seed(23)
arr11 = np.random.randn(3,4)
np.random.seed(23)
arr12 = np.random.randn(3,4)
df11 = pd.DataFrame(arr11,columns=['A','B','C','D'],index=[0,1,2])
df12 = pd.DataFrame(arr12,columns=['A','B','C','D'],index=[3,4,5])

In [174]:
df11

A         B         C         D
0  0.666988  0.025813 -0.777619  0.948634
1  0.701672 -1.051082 -0.367548 -1.137460
2 -1.322148  1.772258 -0.347459  0.670140

In [175]:
df12

A         B         C         D
3  0.666988  0.025813 -0.777619  0.948634
4  0.701672 -1.051082 -0.367548 -1.137460
5 -1.322148  1.772258 -0.347459  0.670140

In [176]:
pd.merge(df11,df12,on='A')

A       B_x       C_x       D_x       B_y       C_y       D_y
0  0.666988  0.025813 -0.777619  0.948634  0.025813 -0.777619  0.948634
1  0.701672 -1.051082 -0.367548 -1.137460 -1.051082 -0.367548 -1.137460
2 -1.322148  1.772258 -0.347459  0.670140  1.772258 -0.347459  0.670140