In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.array([1,2,3,4,"Satya",4+2j])

array(['1', '2', '3', '4', 'Satya', '(4+2j)'], dtype='<U64')

In [8]:
np.array([1,2,3,4.0,5.8,6.78])

array([1.  , 2.  , 3.  , 4.  , 5.8 , 6.78])

In [9]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [10]:
type(np.array([[1,2,3]]))

numpy.ndarray

In [11]:
np.array([[1,2,3],[3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [14]:
np.array([[1,2,3],[3,4,5],[6,7,8]])

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [17]:
np.array([1,2,3,4], ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [18]:
np.array([1,2,3,4,5],dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [19]:
np.array([1,2,3,4,5],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [29]:
arr = np.array([(1,2),(3,4)], dtype=[('a','<i4'),('b','<i8')])

In [30]:
arr[0]

np.void((1, 2), dtype=[('a', '<i4'), ('b', '<i8')])

In [32]:
type(arr[0][0])

numpy.int32

In [33]:
type(arr[0][1])

numpy.int64

In [34]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [36]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [39]:
np.mat(arr)

AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

In [38]:
np.matrix(arr)

matrix([[1, 2],
        [3, 4]])

In [40]:
l = [1,2,3,4,5]

In [41]:
np.array(l)

array([1, 2, 3, 4, 5])

In [42]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [43]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [44]:
mat = np.matrix(arr)
mat

matrix([[1, 2],
        [3, 4]])

In [45]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [46]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [47]:
issubclass(np.matrix,np.ndarray)

True

In [48]:
 # Copy of the array element
arr

array([[1, 2],
       [3, 4]])

In [49]:
a = arr
a

array([[1, 2],
       [3, 4]])

In [50]:
b = np.copy(arr)
b

array([[1, 2],
       [3, 4]])

In [51]:
arr[0][0] = 124

In [52]:
a

array([[124,   2],
       [  3,   4]])

In [53]:
b

array([[1, 2],
       [3, 4]])

In [54]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [55]:
np.fromfunction(lambda i,j:i*j,(3,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [56]:
np.fromfunction(lambda i,j:i**j,(2,4))

array([[1., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [57]:
gen = ( i*i for i in range(5))

In [58]:
gen

<generator object <genexpr> at 0x0000014787EBE190>

In [59]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [60]:
# We can create array from string also
np.fromstring('1,2,3,4,5',sep=',')

array([1., 2., 3., 4., 5.])

In [61]:
np.fromstring('1,2,3,4,5',sep=',',dtype=int)

array([1, 2, 3, 4, 5])

In [62]:
l =[1,2,3,4,5]

In [63]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [64]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr.ndim

1

In [66]:
arr1.ndim

2

In [67]:
arr1.size

9

In [68]:
arr1.shape

(3, 3)

In [69]:
arr1.dtype

dtype('int64')

In [71]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [72]:
arr2.size

12

In [75]:
arr2.shape   # 2,2,3  means there is 2 data with 2,3 dimension

(2, 2, 3)

In [76]:
arr2.ndim

3

In [78]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [79]:
list(range(5.6))

TypeError: 'float' object cannot be interpreted as an integer

In [80]:
np.arange(5.6)

array([0., 1., 2., 3., 4., 5.])

In [81]:
np.arange(5.6,9,0.4)  # The range start from 5.6 and goes to 9 with the range step is 0.4

array([5.6, 6. , 6.4, 6.8, 7.2, 7.6, 8. , 8.4, 8.8])

In [82]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [86]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [89]:
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [90]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [93]:
np.zeros((4,5,8))

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [94]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [95]:
np.ones(2)

array([1., 1.])

In [96]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [97]:
np.empty(3)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [98]:
np.empty((3,4))

array([[6.94977333e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.13073288e+277, 5.02834206e-037, 7.48823847e-067,
        3.27751171e+179],
       [5.92826539e-062, 5.34643207e-038, 1.08646058e-071,
        1.56088486e+161]])

In [99]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [100]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [103]:
np.linspace(1,5,5,endpoint=False,axis=0)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [104]:
np.linspace([1,5],5,endpoint=False,axis=1)

array([[1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
        1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
        2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
        3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
        4.52, 4.6 , 4.68, 4.76, 4.84, 4.92],
       [5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  ,
        5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  ,
        5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  ,
        5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  , 5.  ,
        5.  , 5.  , 5.  , 5.  , 5.  , 5.  ]])

In [107]:
np.logspace(1,4,5)

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

In [108]:
# Now some work on random data
np.random.rand(5)

array([0.63173048, 0.12084258, 0.31756582, 0.23414781, 0.69091329])

In [109]:
np.random.randn(5)

array([-1.23810284,  1.46861118, -2.5712472 ,  0.34457179, -0.12466821])

In [110]:
type(np.random.rand(5))

numpy.ndarray

In [111]:
np.random.randn(3,5)

array([[-0.59739514,  0.32521257, -0.58773361,  1.47680078, -0.23608503],
       [-0.43334264,  1.1044032 ,  1.16489009, -0.33677631,  0.56715774],
       [-1.83875858,  1.20320645, -0.63461838, -0.48850436,  0.25545032]])

In [112]:
np.random.randn(2,3,4)

array([[[ 1.40804271,  0.79003625,  0.61606131, -0.94643112],
        [-0.44205589, -0.38527084, -0.13209204, -0.95323596],
        [-0.38874999, -0.04891352, -0.5541623 , -0.33410923]],

       [[ 0.11950048,  0.17687796,  0.31354615, -0.51416227],
        [ 1.22363917, -0.50818051, -0.83295949,  0.56842985],
        [ 0.16791838,  3.12210451, -0.71489908,  1.03111603]]])

In [113]:
np.random.rand(1,2)

array([[0.19440435, 0.63973736]])

In [114]:
np.random.randint(5)

3

In [115]:
np.random.randint(5)

4

In [116]:
np.random.randint(5)

0

In [117]:
np.random.randint(5,10)

8

In [118]:
np.random.randint(5,10)   # Generate random integer between 5 to 10

6

In [119]:
np.random.randint(5,10,(3,4))  # It generate 3*4 matrix with integer data which value is 5 to 10

array([[7, 7, 5, 7],
       [8, 5, 8, 6],
       [7, 7, 8, 8]], dtype=int32)

In [121]:
arr = np.random.rand(3,1,3)
arr

array([[[0.33101715, 0.8986294 , 0.19405022]],

       [[0.48447023, 0.46798072, 0.30883496]],

       [[0.12152057, 0.66024529, 0.13116207]]])

In [122]:
arr.reshape(3,-1)

array([[0.33101715, 0.8986294 , 0.19405022],
       [0.48447023, 0.46798072, 0.30883496],
       [0.12152057, 0.66024529, 0.13116207]])

In [124]:
arr.min()

np.float64(0.12152057435411756)

In [125]:
arr.max()

np.float64(0.8986294040853734)

In [128]:
arr1 = np.random.randint(3,100,(5,5))
arr1

array([[58, 53,  7, 10, 73],
       [74, 95, 52, 93, 48],
       [42, 33, 15, 84, 78],
       [38, 17, 20, 31, 55],
       [22, 27, 63, 70, 85]], dtype=int32)

In [131]:
arr1[3:,3:]  # This means we are accessing the data from the row 3 till end and from column 3 to end

array([[31, 55],
       [70, 85]], dtype=int32)

In [133]:
arr1[2:4,3:]

array([[84, 78],
       [31, 55]], dtype=int32)

In [134]:
arr1[:,[1,3]] # This means we need all the row but column is only 1 and 3

array([[53, 10],
       [95, 93],
       [33, 84],
       [17, 31],
       [27, 70]], dtype=int32)

In [135]:
arr1[arr1>10]

array([58, 53, 73, 74, 95, 52, 93, 48, 42, 33, 15, 84, 78, 38, 17, 20, 31,
       55, 22, 27, 63, 70, 85], dtype=int32)

In [136]:
a1 = np.random.randint(3,20,(3,3))
a1

array([[ 9,  6,  9],
       [14,  8, 11],
       [ 7, 16, 16]], dtype=int32)

In [137]:
a2 = np.random.randint(3,20,(3,3))
a2

array([[16, 19,  7],
       [18,  4,  8],
       [12, 17,  9]], dtype=int32)

In [139]:
new_array = a1*a2   # This is direct multiplication not matrix multiplication
new_array

array([[144, 114,  63],
       [252,  32,  88],
       [ 84, 272, 144]], dtype=int32)

In [141]:
mat_mul = a1@a2   # This is actual matrix multiplication
mat_mul

array([[360, 348, 192],
       [500, 485, 261],
       [592, 469, 321]], dtype=int32)

In [142]:
a1 = np.random.randint(3,10,(4,5))
a1

array([[8, 7, 7, 6, 7],
       [5, 9, 4, 9, 9],
       [6, 7, 5, 3, 6],
       [6, 3, 9, 8, 7]], dtype=int32)

In [143]:
np.sqrt(a1)

array([[2.82842712, 2.64575131, 2.64575131, 2.44948974, 2.64575131],
       [2.23606798, 3.        , 2.        , 3.        , 3.        ],
       [2.44948974, 2.64575131, 2.23606798, 1.73205081, 2.44948974],
       [2.44948974, 1.73205081, 3.        , 2.82842712, 2.64575131]])

In [144]:
np.exp(a1)

array([[2980.95798704, 1096.63315843, 1096.63315843,  403.42879349,
        1096.63315843],
       [ 148.4131591 , 8103.08392758,   54.59815003, 8103.08392758,
        8103.08392758],
       [ 403.42879349, 1096.63315843,  148.4131591 ,   20.08553692,
         403.42879349],
       [ 403.42879349,   20.08553692, 8103.08392758, 2980.95798704,
        1096.63315843]])

In [145]:
np.log10(a1)

array([[0.90308999, 0.84509804, 0.84509804, 0.77815125, 0.84509804],
       [0.69897   , 0.95424251, 0.60205999, 0.95424251, 0.95424251],
       [0.77815125, 0.84509804, 0.69897   , 0.47712125, 0.77815125],
       [0.77815125, 0.47712125, 0.95424251, 0.90308999, 0.84509804]])